### ISSUE TITLE
JSON dashboard

### ISSUE THREAD

**Issue by slaffoley** [mothe-at/VMPerf-To-Graphite-PowerShell-Script#10]
HI, I have run the powershell script and can see data in graphite, when I import the JSON dashboard, I am getting an error : unable to get property "length" of null or undefined reference. This is on all windows on the dashboard. Any ideas?

**Comment by mothe-at** [comment]
@slaffoley, after Import, can you please try to select a Group (instead of "All") from the "Group" Drop-Down? Values should appear then. After this first try you can switch back to "All" and it will still work. Just save your dashboard afterwards.
Hope that helps. I don't know why this happens with the more recent versions of Grafana, but I will investigate.

**Comment by slaffoley** [comment]
That's great. Thanks for the help
